import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { FormattedMessage, useIntl } from 'react-intl'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



export default function Home(dir) {
  
  const {locales} = useRouter();
  const intl = useIntl();

  const title = intl.formatMessage({ id: "page.home.head.title"});
  const description = intl.formatMessage ({id: "page.home.head.meta.description"});
  
  return (

    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
        <link rel="icon" href="/favicon.ico" hrefLang='x-default'/>
        <link rel="icon" href="/favicon.ico" hrefLang='en'/>
        <link rel="icon" href="/favicon.ico" hrefLang='fr'/>
      </Head>
      <header>
      {[...locales].sort().map((locale) =>(
            <Link key = {locale} href="/" locale = {locale}>
              <div>{locale}</div>
            </Link>
          ))}
          <Link href="new">Recreate page</Link>
      </header>
      <main className={styles.main}>
          <h1>
            <FormattedMessage id="page.home.title" values={{b:(info) => <b>{info}</b>}}></FormattedMessage>
          </h1>
          <p className={styles.description}>
            <FormattedMessage id='page.home.description'></FormattedMessage>
          </p>
      </main>
    </>
  )
}
